apiVersion: v1
kind: Service
metadata:
  name: azure-api-management-gateway
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: apim-gateway-sapapimgmt-sapshgw-default
    app.kubernetes.io/name: azure-api-management-gateway